language: python
python:
  - "2.7"
install:
  - "pip install coveralls"
  - "pip install ."
script:
  - "python setup.py test"
  - "coverage run --source=note setup.py test"
services:
  - mongodb
before_install:
  - "export TZ=US/Eastern"
  - "sudo apt-get install coreutils"
after_success:
  "coveralls"
