#!/usr/bin/env python

import os
import json
import click
from note import webapp

__author__ = "Devin Kelly"


class Config(object):
    def __init__(self, config_file, address, port, debug):
        self.config_file = config_file
        self.address = address
        self.port = port
        self.debug = debug

        self.read_config_file()

    def read_config_file(self):

        with open(os.path.expanduser(self.config_file), 'r') as fd:
            config = json.loads(fd.read())

        if self.address is None:
            self.address = config['webserver']['address']
        if self.port is None:
            self.port = config['webserver']['port']
        if self.debug is None:
            self.debug = config['webserver']['debug']


@click.command()
@click.option("-d", "--debug", is_flag=True, default=False,
              help="Start server in debug mode")
@click.option("-a", "--address", default=None,
              help="Server listen address")
@click.option("-p", "--port", default=None,
              help="Server listen port")
@click.option("-c", "--config", default="~/.config/note.json",
              help="Server listen address")
def main(debug, address, port, config):

    config = Config(config, address, port, debug)

    webapp.debug = config.debug
    webapp.run(host=config.address, port=config.port)

if __name__ == "__main__":
    main()
