#!/usr/bin/env python

__author__ = "Devin Kelly"

from note import Note_Server
import click
import daemon
import os
from daemon import pidfile


@click.command()
@click.option('-d', '--daemonize', is_flag=True, default=False,
              help="Daemonize the note server.")
@click.option('-p', '--pid-file', default=None,
              help='Path to pid file')
def main(daemonize, pid_file):

    if daemonize:

        if pid_file:
            pf = pidfile.PIDLockFile(pid_file)
        else:
            pf = None

        context = daemon.DaemonContext(pidfile=pf)

        with context:
            s = Note_Server()
            s.Run()
    else:
        s = Note_Server()
        s.Run()

    return 0

if __name__ == "__main__":
    main()
